<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
    <ProjectReference Include="../../src/ServiceMantle/ServiceMantle.csproj" />
    <ProjectReference Include="../../src/ServiceMantle.Web/ServiceMantle.Web.csproj" />
    <ProjectReference Include="../../src/ServiceMantle.Logging/ServiceMantle.Logging.csproj" />
    <ProjectReference Include="../../src/ServiceMantle.Database.Sqlite/ServiceMantle.Database.Sqlite.csproj" />
    <ProjectReference Include="../../src/ServiceMantle.Database.PostgreSql/ServiceMantle.Database.PostgreSql.csproj" />
    <ProjectReference Include="../../src/ServiceMantle.Persistence.Relational/ServiceMantle.Persistence.Relational.csproj" />
    <ProjectReference Include="../../src/ServiceMantle.Diagnostics/ServiceMantle.Diagnostics.csproj" />
    <ProjectReference Include="../../src/ServiceMantle.Discovery/ServiceMantle.Discovery.csproj" />
  </ItemGroup>
</Project>
