<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
    <ProjectReference Include="../../src/ServiceMantle/ServiceMantle.csproj" />
    <ProjectReference Include="../../src/ServiceMantle.AspNetCore/ServiceMantle.AspNetCore.csproj" />
    <ProjectReference Include="../../src/ServiceMantle.Serilog/ServiceMantle.Serilog.csproj" />
    <ProjectReference Include="../../src/ServiceMantle.Database.Sqlite/ServiceMantle.Database.Sqlite.csproj" />
    <ProjectReference Include="../../src/ServiceMantle.OpenTelemetry/ServiceMantle.OpenTelemetry.csproj" />
  </ItemGroup>
</Project>
