namespace ServiceMantle.Migration;

/// <summary>
/// The identity generation kind of a column, neutralized across providers that report
/// SQL-standard identity columns.
/// </summary>
public enum SchemaIdentityKind
{
    /// <summary>The column has no identity generation.</summary>
    None = 0,

    /// <summary>The column is generated always as identity.</summary>
    Always = 1,

    /// <summary>The column is generated by default as identity.</summary>
    ByDefault = 2
}

/// <summary>
/// The referential delete rule of a foreign key, neutralized across providers.
/// </summary>
public enum SchemaForeignKeyDeleteRule
{
    /// <summary>No action is taken on referenced-row deletion.</summary>
    NoAction = 0,

    /// <summary>Referenced-row deletion is restricted while referencing rows exist.</summary>
    Restrict = 1,

    /// <summary>Referencing rows are deleted with the referenced row.</summary>
    Cascade = 2,

    /// <summary>Referencing columns are set to null.</summary>
    SetNull = 3,

    /// <summary>Referencing columns are set to their default value.</summary>
    SetDefault = 4
}

/// <summary>
/// One immutable column of the neutral schema evidence model: name, provider type string,
/// nullability, identity kind, and the stored-default evidence flag.
/// </summary>
/// <remarks>
/// <para>
/// The comparison dimensions of a column are its name, type string, nullability, and identity
/// kind. <see cref="HasStoredDefault"/> is an evidence field only: it never produces a
/// difference by itself, and the default's value is never part of the model. Readers that do
/// not observe column defaults report <c>false</c>.
/// </para>
/// <para>
/// Type strings compare exactly, as the provider reports them; dialect normalization (for
/// example <c>integer</c> versus <c>int4</c>) is deliberately not provided.
/// </para>
/// </remarks>
public sealed class SchemaColumn
{
    /// <summary>Initializes the immutable column.</summary>
    /// <param name="name">The column name.</param>
    /// <param name="dataType">The provider-reported type string.</param>
    /// <param name="isNullable">Whether the column accepts null values.</param>
    /// <param name="identityKind">The identity generation kind.</param>
    /// <param name="hasStoredDefault">
    /// Whether the column has a stored default; evidence only, never a comparison dimension.
    /// </param>
    public SchemaColumn(
        string name,
        string dataType,
        bool isNullable,
        SchemaIdentityKind identityKind = SchemaIdentityKind.None,
        bool hasStoredDefault = false)
    {
        SchemaEvidenceModel.ValidateIdentifier(name, nameof(name));
        SchemaEvidenceModel.ValidateIdentifier(dataType, nameof(dataType));
        if (!Enum.IsDefined(identityKind))
        {
            throw new ArgumentOutOfRangeException(nameof(identityKind));
        }

        Name = name;
        DataType = dataType;
        IsNullable = isNullable;
        IdentityKind = identityKind;
        HasStoredDefault = hasStoredDefault;
    }

    /// <summary>Gets the column name.</summary>
    public string Name { get; }

    /// <summary>Gets the provider-reported type string.</summary>
    public string DataType { get; }

    /// <summary>Gets whether the column accepts null values.</summary>
    public bool IsNullable { get; }

    /// <summary>Gets the identity generation kind.</summary>
    public SchemaIdentityKind IdentityKind { get; }

    /// <summary>
    /// Gets whether the column has a stored default. Evidence for backfill judgment only; not a
    /// comparison dimension.
    /// </summary>
    public bool HasStoredDefault { get; }

    /// <summary>Returns the identifier-only column summary.</summary>
    public override string ToString() =>
        $"{Name}: {DataType}, {(IsNullable ? "nullable" : "not null")}, identity {IdentityKind}" +
        (HasStoredDefault ? ", stored default" : string.Empty);
}

/// <summary>One immutable primary key of the neutral schema evidence model.</summary>
public sealed class SchemaPrimaryKey
{
    /// <summary>Initializes the immutable primary key.</summary>
    /// <param name="columns">The key columns, in constraint order.</param>
    public SchemaPrimaryKey(IReadOnlyList<string> columns)
    {
        SchemaEvidenceModel.ValidateColumnList(columns, nameof(columns));

        Columns = [.. columns];
    }

    /// <summary>Gets the key columns, in constraint order.</summary>
    public IReadOnlyList<string> Columns { get; }

    /// <summary>Returns the identifier-only key summary.</summary>
    public override string ToString() => $"primary key ({string.Join(", ", Columns)})";
}

/// <summary>
/// One immutable foreign key of the neutral schema evidence model: constrained columns,
/// referenced table and columns, and the delete rule.
/// </summary>
public sealed class SchemaForeignKey
{
    /// <summary>Initializes the immutable foreign key.</summary>
    /// <param name="columns">The constrained columns, in constraint order.</param>
    /// <param name="referencedTable">The referenced table name.</param>
    /// <param name="referencedColumns">The referenced columns, in constraint order.</param>
    /// <param name="deleteRule">The referential delete rule.</param>
    /// <param name="referencedSchema">
    /// The referenced table's schema, or null for the provider's default schema.
    /// </param>
    public SchemaForeignKey(
        IReadOnlyList<string> columns,
        string referencedTable,
        IReadOnlyList<string> referencedColumns,
        SchemaForeignKeyDeleteRule deleteRule,
        string? referencedSchema = null)
    {
        SchemaEvidenceModel.ValidateColumnList(columns, nameof(columns));
        SchemaEvidenceModel.ValidateColumnList(referencedColumns, nameof(referencedColumns));
        SchemaEvidenceModel.ValidateIdentifier(referencedTable, nameof(referencedTable));
        SchemaEvidenceModel.ValidateOptionalIdentifier(referencedSchema, nameof(referencedSchema));
        if (!Enum.IsDefined(deleteRule))
        {
            throw new ArgumentOutOfRangeException(nameof(deleteRule));
        }

        Columns = [.. columns];
        ReferencedTable = referencedTable;
        ReferencedColumns = [.. referencedColumns];
        DeleteRule = deleteRule;
        ReferencedSchema = referencedSchema;
    }

    /// <summary>Gets the constrained columns, in constraint order.</summary>
    public IReadOnlyList<string> Columns { get; }

    /// <summary>Gets the referenced table name.</summary>
    public string ReferencedTable { get; }

    /// <summary>Gets the referenced columns, in constraint order.</summary>
    public IReadOnlyList<string> ReferencedColumns { get; }

    /// <summary>Gets the referential delete rule.</summary>
    public SchemaForeignKeyDeleteRule DeleteRule { get; }

    /// <summary>Gets the referenced table's schema, or null for the provider's default schema.</summary>
    public string? ReferencedSchema { get; }

    /// <summary>Returns the identifier-only key summary.</summary>
    public override string ToString() =>
        $"foreign key ({string.Join(", ", Columns)}) references " +
        $"{(ReferencedSchema is null ? string.Empty : ReferencedSchema + ".")}{ReferencedTable}" +
        $"({string.Join(", ", ReferencedColumns)}) on delete {DeleteRule}";
}

/// <summary>
/// One immutable non-constraint index of the neutral schema evidence model: covered columns
/// and uniqueness. Index names are deliberately not part of the model.
/// </summary>
public sealed class SchemaIndex
{
    /// <summary>Initializes the immutable index.</summary>
    /// <param name="columns">The indexed columns, in index order.</param>
    /// <param name="isUnique">Whether the index enforces uniqueness.</param>
    public SchemaIndex(IReadOnlyList<string> columns, bool isUnique)
    {
        SchemaEvidenceModel.ValidateColumnList(columns, nameof(columns));

        Columns = [.. columns];
        IsUnique = isUnique;
    }

    /// <summary>Gets the indexed columns, in index order.</summary>
    public IReadOnlyList<string> Columns { get; }

    /// <summary>Gets whether the index enforces uniqueness.</summary>
    public bool IsUnique { get; }

    /// <summary>Returns the identifier-only index summary.</summary>
    public override string ToString() =>
        $"{(IsUnique ? "unique " : string.Empty)}index ({string.Join(", ", Columns)})";
}

/// <summary>
/// One immutable table of the neutral schema evidence model: columns, primary key, foreign
/// keys, and non-constraint indexes. Used by both <see cref="SchemaSnapshot"/> and
/// <see cref="ExpectedSchema"/>, which are isomorphic by contract.
/// </summary>
public sealed class SchemaTable
{
    /// <summary>Initializes the immutable table.</summary>
    /// <param name="name">The table name.</param>
    /// <param name="columns">The table's columns; at least one is required.</param>
    /// <param name="primaryKey">The primary key, or null when the table has none.</param>
    /// <param name="foreignKeys">The foreign keys; empty when the table has none.</param>
    /// <param name="indexes">The non-constraint indexes; empty when the table has none.</param>
    /// <param name="schema">The table's schema, or null for the provider's default schema.</param>
    public SchemaTable(
        string name,
        IReadOnlyList<SchemaColumn> columns,
        SchemaPrimaryKey? primaryKey = null,
        IReadOnlyList<SchemaForeignKey>? foreignKeys = null,
        IReadOnlyList<SchemaIndex>? indexes = null,
        string? schema = null)
    {
        SchemaEvidenceModel.ValidateIdentifier(name, nameof(name));
        SchemaEvidenceModel.ValidateOptionalIdentifier(schema, nameof(schema));
        ArgumentNullException.ThrowIfNull(columns);
        if (columns.Count == 0)
        {
            throw new ArgumentException("The table requires at least one column.", nameof(columns));
        }

        var columnNames = new HashSet<string>(StringComparer.Ordinal);
        foreach (var column in columns)
        {
            ArgumentNullException.ThrowIfNull(column, nameof(columns));
            if (!columnNames.Add(column.Name))
            {
                throw new ArgumentException(
                    $"The table contains a duplicate column name: {column.Name}.",
                    nameof(columns));
            }
        }

        ValidateForeignKeys(foreignKeys);
        ValidateIndexes(indexes);

        Name = name;
        Columns = [.. columns];
        PrimaryKey = primaryKey;
        ForeignKeys = foreignKeys is null ? [] : [.. foreignKeys];
        Indexes = indexes is null ? [] : [.. indexes];
        Schema = schema;
    }

    /// <summary>Gets the table name.</summary>
    public string Name { get; }

    /// <summary>Gets the table's columns.</summary>
    public IReadOnlyList<SchemaColumn> Columns { get; }

    /// <summary>Gets the primary key, or null when the table has none.</summary>
    public SchemaPrimaryKey? PrimaryKey { get; }

    /// <summary>Gets the foreign keys; empty when the table has none.</summary>
    public IReadOnlyList<SchemaForeignKey> ForeignKeys { get; }

    /// <summary>Gets the non-constraint indexes; empty when the table has none.</summary>
    public IReadOnlyList<SchemaIndex> Indexes { get; }

    /// <summary>Gets the table's schema, or null for the provider's default schema.</summary>
    public string? Schema { get; }

    /// <summary>Returns the identifier-only table name.</summary>
    public override string ToString() =>
        (Schema is null ? string.Empty : Schema + ".") + Name;

    private void ValidateForeignKeys(IReadOnlyList<SchemaForeignKey>? foreignKeys)
    {
        if (foreignKeys is null)
        {
            return;
        }

        var identities = new HashSet<string>(StringComparer.Ordinal);
        foreach (var foreignKey in foreignKeys)
        {
            ArgumentNullException.ThrowIfNull(foreignKey, nameof(foreignKeys));
            if (!identities.Add(ForeignKeyIdentity(foreignKey)))
            {
                throw new ArgumentException(
                    "The table contains a duplicate foreign key identity.",
                    nameof(foreignKeys));
            }
        }
    }

    private void ValidateIndexes(IReadOnlyList<SchemaIndex>? indexes)
    {
        if (indexes is null)
        {
            return;
        }

        var identities = new HashSet<string>(StringComparer.Ordinal);
        foreach (var index in indexes)
        {
            ArgumentNullException.ThrowIfNull(index, nameof(indexes));
            if (!identities.Add(IndexIdentity(index)))
            {
                throw new ArgumentException(
                    "The table contains a duplicate index identity.",
                    nameof(indexes));
            }
        }
    }

    /// <summary>The full identity of a foreign key: shape plus delete rule.</summary>
    internal static string ForeignKeyIdentity(SchemaForeignKey foreignKey) =>
        string.Join("\u0000", foreignKey.Columns) + "\u0001" +
        (foreignKey.ReferencedSchema ?? string.Empty) + "\u0001" + foreignKey.ReferencedTable +
        "\u0001" + string.Join("\u0000", foreignKey.ReferencedColumns) + "\u0001" +
        (int)foreignKey.DeleteRule;

    /// <summary>The shape of a foreign key: everything but the delete rule.</summary>
    internal static string ForeignKeyShape(SchemaForeignKey foreignKey) =>
        string.Join("\u0000", foreignKey.Columns) + "\u0001" +
        (foreignKey.ReferencedSchema ?? string.Empty) + "\u0001" + foreignKey.ReferencedTable +
        "\u0001" + string.Join("\u0000", foreignKey.ReferencedColumns);

    /// <summary>The shape of an index: its columns, in order.</summary>
    internal static string IndexShape(SchemaIndex index) => string.Join("\u0000", index.Columns);

    /// <summary>The full identity of an index: shape plus uniqueness.</summary>
    internal static string IndexIdentity(SchemaIndex index) => IndexShape(index) + "\u0001" + index.IsUnique;
}

/// <summary>
/// The immutable, provider-neutral snapshot of a database's actual structure as one reader
/// observed it: tables with columns (name, type string, nullability, identity kind), primary
/// keys, foreign keys, and non-constraint indexes.
/// </summary>
/// <remarks>
/// Non-guarantees: the snapshot carries no information about check constraints, column default
/// values, triggers, views, stored procedures, permissions, partitions, or any other structure
/// outside the modeled dimensions, and it is not a point-in-time transactional image unless the
/// reader made it one.
/// </remarks>
public sealed class SchemaSnapshot
{
    /// <summary>Initializes the immutable snapshot.</summary>
    /// <param name="tables">The observed tables.</param>
    public SchemaSnapshot(IReadOnlyList<SchemaTable> tables)
    {
        Tables = SchemaEvidenceModel.ValidateTables(tables);
    }

    /// <summary>Gets the observed tables.</summary>
    public IReadOnlyList<SchemaTable> Tables { get; }
}

/// <summary>
/// The immutable, provider-neutral expected structure, isomorphic to
/// <see cref="SchemaSnapshot"/>: it is derived from the application's own model (for example by
/// EF model derivation in the persistence package) and compared against the snapshot by
/// <see cref="SchemaEvidenceComparer"/>.
/// </summary>
public sealed class ExpectedSchema
{
    /// <summary>Initializes the immutable expected schema.</summary>
    /// <param name="tables">The expected tables.</param>
    public ExpectedSchema(IReadOnlyList<SchemaTable> tables)
    {
        Tables = SchemaEvidenceModel.ValidateTables(tables);
    }

    /// <summary>Gets the expected tables.</summary>
    public IReadOnlyList<SchemaTable> Tables { get; }
}

/// <summary>Shared validation and keying rules of the neutral schema evidence model.</summary>
internal static class SchemaEvidenceModel
{
    internal const int MaximumIdentifierLength = 128;

    internal static IReadOnlyList<SchemaTable> ValidateTables(IReadOnlyList<SchemaTable>? tables)
    {
        ArgumentNullException.ThrowIfNull(tables);

        var fullNames = new HashSet<string>(StringComparer.Ordinal);
        foreach (var table in tables)
        {
            ArgumentNullException.ThrowIfNull(table, nameof(tables));
            if (!fullNames.Add(TableKey(table)))
            {
                throw new ArgumentException(
                    $"The schema contains a duplicate table: {table}.",
                    nameof(tables));
            }
        }

        return [.. tables];
    }

    internal static string TableKey(SchemaTable table) =>
        (table.Schema ?? string.Empty) + "\u0000" + table.Name;

    internal static void ValidateIdentifier(string? value, string parameterName)
    {
        if (value is null)
        {
            throw new ArgumentNullException(parameterName);
        }

        if (!IsValidIdentifier(value))
        {
            throw new ArgumentException(InvalidIdentifierMessage, parameterName);
        }
    }

    internal static void ValidateOptionalIdentifier(string? value, string parameterName)
    {
        if (value is not null && !IsValidIdentifier(value))
        {
            throw new ArgumentException(InvalidIdentifierMessage, parameterName);
        }
    }

    internal static void ValidateColumnList(IReadOnlyList<string>? columns, string parameterName)
    {
        ArgumentNullException.ThrowIfNull(columns);
        if (columns.Count == 0)
        {
            throw new ArgumentException("At least one column name is required.", parameterName);
        }

        foreach (var column in columns)
        {
            ValidateIdentifier(column, parameterName);
        }
    }

    private const string InvalidIdentifierMessage =
        "An identifier must contain 1 to 128 visible characters and no control characters.";

    private static bool IsValidIdentifier(string value) =>
        value.Length is >= 1 and <= MaximumIdentifierLength &&
        !string.IsNullOrWhiteSpace(value) &&
        !value.Any(char.IsControl);
}
